import json,re,pathlib,unicodedata,collections
ROOT=pathlib.Path(__file__).resolve().parents[1];cs=json.loads((ROOT/'corpus.json').read_text()); entries=[]
def norm(s):return ''.join(c for c in unicodedata.normalize('NFD',s.casefold()) if unicodedata.category(c)!='Mn')
def add(cat,name,subtitle,summary,aliases=None,group='',related=None):
 aliases=aliases or [name]; patterns=[re.compile(r'(?<!\w)'+r'\s+'.join(re.escape(w) for w in norm(a).split())+r'(?!\w)') for a in aliases]; refs=[];chapters=[]; occurrences=0
 for c in cs:
  hit=False
  for p in c['pages']:
   t=p['text'];nt=norm(t); matches=[m for pat in patterns for m in pat.finditer(nt)]
   if matches:
    occurrences+=len(matches);hit=True
    if len(refs)<12:
     # Original page citation; the full page is available in the reader.
     pos=min(m.start() for m in matches); original_pos=min(pos,len(t)-1); start=max(0,t.rfind('\n',0,original_pos-50));snippet=t[start:min(len(t),original_pos+430)].replace('\x00','').strip()
     refs.append({'chapter':c['id'],'tome':c['tome'],'page':p['page'],'quote':snippet})
  if hit:chapters.append(c['id'])
 if not chapters:
  print('UNSUPPORTED',name);return
 id=norm(name);id=re.sub(r'[^a-z0-9]+','-',id).strip('-')
 entries.append({'id':id,'category':cat,'name':name,'subtitle':subtitle,'summary':summary,'aliases':aliases,'group':group,'related':related or [],'sources':refs,'chapters':chapters,'occurrences':occurrences,'first':chapters[0],'tomes':sorted(set(int(re.search(r't(\d+)',c)[1]) for c in chapters))})
# All descriptions below are conservative editorial syntheses; the page excerpts provide the underlying evidence.
characters=[
('Amado Shirogane','Raison · Gardien de l’Équilibre','Créé par la Conscience pour maintenir la cohérence de l’univers. Porteur de Logos, il assume à la fois une fonction d’arbitre conceptuel et une place centrale dans la famille Shirogane.',['Amado Shirogane','Amado'],'Fondations',['Logos','Noésis Absoluta','Rebecca Shirogane','Amadeus']),
('Noésis Absoluta','Sens · Déesse primordiale','Incarnation du Sens. Sa présence autoritaire et ses interventions donnent une direction à l’existence. Ses affrontements avec Nulla Absentia et son rôle dans le conflit du Doute traversent le récit.',['Noésis Absoluta','Noésis Shirogane','Noésis'],'Primordiales',['Téganon','Amado Shirogane','Amadeus','Nulla Absentia']),
('Rebecca Shirogane','Création · Artiste','Créatrice liée à l’imagination, aux émotions et à la mise en forme du vivant. Elle donne naissance aux Ama Girls et emploie Ink Genesis. Ses créations et leurs conséquences nourrissent plusieurs conflits.',['Rebecca Shirogane','Rebecca'],'Fondations',['Ink Genesis','Ama Girls','Iris Marthory-Vaucluse','Nulla Absentia']),
('Nyxara Abyssgarde','Néant · Déesse primordiale','Présence originelle du Néant. Son lien avec Amavelle associe transmission, protection et apprentissage du vide. Sa nature véritable et les profondeurs de son domaine sont explorées progressivement.',['Nyxara Abyssgarde','Nyxara'],'Primordiales',['Amavelle Shirogane','Néant','Barbatos']),
('Orphéa Aurora','Temps absolu · Déesse primordiale','Souveraine de l’Univers du Temps Absolu, porteuse de Temporis. Elle organise les responsabilités temporelles et se confronte à l’Éternité incarnée par Kairosia.',['Orphéa Aurora','Orphéa'],'Primordiales',['Temporis','Univers du Temps Absolu','Kairosia Aethern','Arion Valerius']),
('Kairosia Aethern','Éternité · Déesse primordiale','Contrepoint d’Orphéa, liée à l’Éternité. Elle manie Aethernis et crée des figures opposées aux fonctions de l’univers temporel. Son règne est également exploré dans le spin-off.',['Kairosia Aethern','Kairosia'],'Primordiales',['Aethernis','Orphéa Aurora','Kairon Vanthel','Némoris Halcyon','Gravem Noctar']),
('Iris Marthory-Vaucluse','Esthétique · Architecte des formes','Incarnation de l’esthétisme. Elle examine les formes, les lignes et la beauté des existences. Sa relation avec Rebecca met en regard la forme idéale et la création porteuse d’émotions.',['Iris Marthory-Vaucluse','Iris Marthory Vaucluse','Iris'],'Fondations',['Rebecca Shirogane','Désert de l’Idéal','Esthétique']),
('Amanda Shirogane','Vérité · Ama Girl','Incarnation de la Vérité, liée au monde rubis et à Veritas. Elle participe à la découverte des mondes, aux missions terrestres et aux affrontements des Ama Girls.',['Amanda Shirogane','Amanda'],'Ama Girls',['Veritas','Monde Rubis','Awa Danhomè','Amanda Absolute']),
('Amandine Shirogane','Liberté · Ama Girl','Incarnation de la Liberté. Son monde solaire et son arc Heliona accompagnent une personnalité vive et des combats fondés sur le mouvement et l’élan.',['Amandine Shirogane','Amandine'],'Ama Girls',['Heliona','Monde Doré','Lysandra Monteiro','Amandine Absolute']),
('Amada Shirogane','Nature · Ama Girl','Ama Girl liée au vivant, aux créatures et à un monde émeraude. Elle manie Lifebloom et apprend à articuler protection du vivant et responsabilité.',['Amada Shirogane','Amada'],'Ama Girls',['Lifebloom','Monde Émeraude','Avelyn Waver','Amada Absolute']),
('Amalia Shirogane','Harmonie · Ama Girl','Incarnation de l’Harmonie. Elle recherche la résonance et l’équilibre des forces, avec une progression qui valorise l’écoute et l’ajustement.',['Amalia Shirogane','Amalia'],'Ama Girls',['Monde Saphir','Lian Yue','Amalia Absolute']),
('Amarilys Shirogane','Perfection · Ama Girl','Épéiste liée à la Perfection et au monde argenté. Porteuse de Seijun, elle confronte sa précision aux limites des règles et de l’expérience humaine.',['Amarilys Shirogane','Amarilys'],'Ama Girls',['Seijun','Monde Argenté','Anastasia Vladimirovitch','Amarilys Absolute']),
('Amarisa Shirogane','Logique · Ama Girl','Incarnation de la Logique et exploratrice des structures conceptuelles. Logion et ses raisonnements occupent une place importante dans les duels de lois.',['Amarisa Shirogane','Amarisa'],'Ama Girls',['Logion','Monde Améthyste','Jasmine Al-Taybah','Amarisa Absolute']),
('Amavelle Shirogane','Silence · Septième Ama Girl','Septième sœur, liée au Silence et à Nyxara. Son apprentissage du Néant, son marteau Silentium et ses interventions contre les Rupturus jouent un rôle décisif dans la série.',['Amavelle Shirogane','Amavelle'],'Ama Girls',['Silentium','Nyxara Abyssgarde','Monde du Silence','Noxelyra Ordine']),
('Mirea Silenshade','Silence · Servante conceptuelle','Servante chargée d’enseigner aux Ama Girls à exister sans se perdre. Elle apaise les débordements et utilise la hache conceptuelle Originis.',['Mirea Silenshade','Mirea'],'Servantes',['Originis','Ama Girls','Silence']),
('Vara Ordeline','Ordre · Servante conceptuelle','Servante de l’Ordre. Elle apprend aux Ama Girls à structurer leur force et à poser des limites, avec une discipline rigoureuse et les armes Fatalis.',['Vara Ordeline','Vara'],'Servantes',['Fatalis','Ordre','Ama Girls']),
('Lysenne Dreamveil','Rêves · Servante conceptuelle','Servante des Rêves, du repos mental et de l’apaisement. Elle enseigne la douceur et intervient avec Echron.',['Lysenne Dreamveil','Lysenne'],'Servantes',['Echron','Ama Girls','Rêves']),
('Awa Danhomè','Afrique · Warden','Warden africaine, associée à la mémoire et à la terre. Elle accompagne Amanda et affronte Kaelen dans le conflit de Béhémoth.',['Awa Danhomè','Awa Danhomé','Awa'],'Wardens',['Amanda Shirogane','Kaelen','Wardens']),
('Lysandra Monteiro','Amérique du Sud · Warden','Warden liée au vent et à la liberté. Elle accompagne Amandine et affronte notamment Huracàn Obscura et Tiago.',['Lysandra Monteiro','Lysandra'],'Wardens',['Amandine Shirogane','Tiago','Huracàn Obscura']),
('Anastasia Vladimirovitch','Europe · Warden','Warden européenne liée à la gravité. Sa discipline et ses confrontations avec Nullstahl et Aris structurent plusieurs épisodes.',['Anastasia Vladimirovitch','Anastasia'],'Wardens',['Amarilys Shirogane','Aris','Egregor Nullstahl']),
('Lian Yue','Asie · Warden','Warden chargée de stabiliser le Qi collectif de l’Asie. Elle participe aux apprentissages d’Amalia et au combat contre Jīn-Luàn.',['Lian Yue'],'Wardens',['Amalia Shirogane','Jīn-Luàn','Qi']),
('Avelyn Waver','Océanie · Warden','Warden de l’Océanie. Son hydro-mimétisme, sa joie et son adaptation lient ses interventions à l’océan et à Amada.',['Avelyn Waver','Avelyn'],'Wardens',['Amada Shirogane','Nara-Éther','Hydro-mimétisme']),
('Jasmine Al-Taybah','Moyen-Orient · Warden','Warden du sable et des mirages, liée à la vérité spirituelle. Elle accompagne Amarisa et affronte Zahhak al-Sirr.',['Jasmine Al-Taybah','Jasmine Al Taybah','Jasmine'],'Wardens',['Amarisa Shirogane','Zahhak al-Sirr','Wardens']),
('Séraphyne Glacialis','Antarctique · Warden','Warden de l’Antarctique. Son combat initial avec Béhémoth et sa participation à la convergence des sept Wardens mettent en jeu la suspension et la stabilité.',['Séraphyne Glacialis','Séraphyne'],'Wardens',['Béhémoth','Suspension Blanche','Wardens']),
('Arion Valerius','Continuité · Gardien temporel','Gardien de la continuité temporelle. Son épée Aethernox corrige les structures qu’elle touche. Il intervient notamment face à Chronosia, Chrona Residua et Kairosia.',['Arion Valerius','Arion'],'Temps',['Aethernox','Chronosia','Chrona Residua']),
('Chronosia','Temps rejeté · Némésis temporelle','Existence née du temps et de son retard. Ses futurs contradictoires et son arme Aphanéion interrogent la place des réalités exclues.',['Chronosia'],'Temps',['Aphanéion','Arion Valerius','Univers du Temps Absolu']),
('Elythra Continuum','Flux · Servante temporelle','Servante du Flux. Elle protège la fluidité et le devenir des lignes temporelles et se confronte à Némoris Halcyon.',['Elythra Continuum','Elythra'],'Temps',['Némoris Halcyon','Univers du Temps Absolu']),
('Virelya Aeon','Stase · Servante temporelle','Servante de la Stase. Elle décide quand le Temps doit attendre ou s’arrêter, et quand une exception peut être maintenue.',['Virelya Aeon','Virelya'],'Temps',['Univers du Temps Absolu','Gravem Noctar']),
('Chroniel Sidera','Repère · Fonction temporelle','Figure du repère temporel et de l’enregistrement des faits. Sa fonction intervient dans l’organisation de l’Univers du Temps Absolu.',['Chroniel Sidera','Chroniel'],'Temps',['Univers du Temps Absolu','Kairon Vanthel']),
('Kairon Vanthel','Paradoxe · Éternité','Créé par Kairosia pour briser les relations entre cause et conséquence. Son action introduit des paradoxes dans l’univers temporel.',['Kairon Vanthel','Kairon'],'Éternité',['Kairosia Aethern','Chroniel Sidera']),
('Némoris Halcyon','Moments éternels · Éternité','Contrepoint du Flux. Son domaine retient les instants et oppose la permanence au mouvement incarné par Elythra.',['Némoris Halcyon','Nemoris Halcyon','Némoris'],'Éternité',['Elythra Continuum','Kairosia Aethern']),
('Gravem Noctar','Silence temporel · Éternité','Figure créée dans le règne de Kairosia. Son action ralentit les flux et impose un calme qui touche le temps lui-même.',['Gravem Noctar','Gravem'],'Éternité',['Virelya Aeon','Kairosia Aethern']),
('Esméralda','Servante · Éternité','Servante rattachée à l’univers de l’Éternité. Ses apparitions sont réunies dans les passages sources pour suivre son rôle et son évolution.',['Esméralda','Esmeralda'],'Éternité',['Kairosia Aethern']),
('Nulla Absentia','Nihilisme','Existence associée au Nihilisme, à l’absence de sens et aux conséquences de la création. Sa rivalité avec Noésis se poursuit jusque dans les chapitres bonus.',['Nulla Absentia','Nulla'],'Antagonistes',['Noésis Absoluta','Rebecca Shirogane','Noxelyra Ordine']),
('Cael Virelios','Doute · Antagoniste','Le Doute devenu existence autonome. Il examine l’univers, met ses certitudes en procès et emploie Aporia et la Balance de la Certitude.',['Cael Virelios','Cael'],'Antagonistes',['Aporia','Balance de la Certitude','Nyra Velmire','Amadeus']),
('Nyra Velmire','Instabilité primordiale','Création de Cael issue d’une fissure ouverte par Aporia. Son instabilité bouleverse les domaines et affronte les Rupturus stabilisés, Nulla et les défenseurs du Sens.',['Nyra Velmire','Nyra'],'Antagonistes',['Cael Virelios','Noxelyra Ordine','Eidolynae Varael','Nyra Cerberus']),
('Nyra Cerberus','Forme · Instabilité','Forme de Nyra explorée pendant les combats du tome 9. Le chapitre « La Purge à Trois Gueules » prolonge cette transformation.',['Nyra Cerberus'],'Formes',['Nyra Velmire']),
('Noxelyra Ordine','Rupturus stabilisé · Niveau 5','Rupturus stabilisé qui revendique une cohérence propre. Son parcours avec Varael conduit à des évolutions majeures pendant le conflit du Doute.',['Noxelyra Ordine','Noxelyra'],'Rupturus',['Eidolynae Varael','Noxelyra Apex','Rupturus']),
('Eidolynae Varael','Rupturus stabilisé · Niveau 4','Existence stabilisée qui révèle les incompatibilités des lois plutôt que d’en créer. Son lien avec Noxelyra est central à leur domaine.',['Eidolynae Varael','Varael'],'Rupturus',['Noxelyra Ordine','Nyra Velmire']),
('Noxelyra Apex','Évolution · Rupturus','État évolué de Noxelyra impliqué dans les affrontements contre Nyra, aux côtés de Nulla Absentia.',['Noxelyra Apex'],'Formes',['Noxelyra Ordine','Nulla Absentia','Nyra Velmire']),
('Béhémoth','Anomalie primordiale','Anomalie qui entend stabiliser le monde en mettant fin aux extrêmes émotionnels. Elle porte Éon et affronte les sept Wardens au terme d’une crise planétaire.',['Béhémoth','Behemoth'],'Antagonistes',['Éon','Wardens','Kaelen','Tiago','Aris','Nara-Éther','Jīn-Luàn','Zahhak al-Sirr']),
('Kaelen','Lieutenant · Béhémoth','Adversaire d’Awa Danhomè dans le conflit de Béhémoth. Ses attaques et le déroulement de leur duel sont documentés dans le tome 6.',['Kaelen'],'Antagonistes',['Awa Danhomè','Béhémoth']),
('Tiago','Lieutenant · Béhémoth','Adversaire de Lysandra Monteiro pendant la crise de Béhémoth.',['Tiago'],'Antagonistes',['Lysandra Monteiro','Béhémoth']),
('Aris','Lieutenant · Béhémoth','Adversaire d’Anastasia Vladimirovitch dans le tome 6.',['Aris'],'Antagonistes',['Anastasia Vladimirovitch','Béhémoth']),
('Nara-Éther','Lieutenant · Immobilité','Adversaire d’Avelyn, lié à l’immobilité et à la fin du flux océanique.',['Nara-Éther','Nara Ether'],'Antagonistes',['Avelyn Waver','Béhémoth']),
('Jīn-Luàn','Lieutenant · Désaccord','Adversaire de Lian Yue. Il déforme les flux de Qi et attaque l’équilibre du continent.',['Jīn-Luàn','Jin-Luan'],'Antagonistes',['Lian Yue','Béhémoth']),
('Zahhak al-Sirr','Lieutenant · Mirages','Adversaire de Jasmine, dont les mirages altèrent les repères et rendent les choses fausses. Le titre d’un chapitre emploie la variante « Zahhar Al-Sirr ».',['Zahhak','Zahhar Al-Sirr','Zahhak al-Sirr'],'Antagonistes',['Jasmine Al-Taybah','Béhémoth']),
('Limos','Famine · Cavalier','Cavalier de la Famine Ocre, apparu sur des terres ravagées par le désespoir. Sa défaite est racontée au chapitre 1111.',['Limos'],'Antagonistes',['Cavaliers','Nyra Velmire']),
('Kratos','Oppression · Cavalier','Cavalier de l’Oppression Noire, au corps colossal et à l’armure dense. Sa défaite est racontée au chapitre 1112.',['Kratos'],'Antagonistes',['Cavaliers','Nyra Velmire']),
('Eros','Cavalier','L’un des trois Cavaliers du conflit du Doute. Son apparition et sa défaite sont accessibles dans les passages du tome 8.',['Eros'],'Antagonistes',['Cavaliers','Nyra Velmire']),
('Amadeus','Héritage · Raison et Sens','Fils d’Amado et de Noésis. Son apprentissage associe héritage conceptuel, expérience humaine et affrontement du Doute.',['Amadeus'],'Descendance',['Amado Shirogane','Noésis Absoluta','Elior Vale','Cael Virelios']),
('Amaelle Shirogane','Astra Nova · Héroïne','Amaelle mène une vie humaine et devient l’héroïne Astra Nova. Son immortalité n’efface pas sa vulnérabilité, ses responsabilités ni les conséquences indirectes d’un sauvetage.',['Amaelle Shirogane','Amaelle','Astra Nova'],'Descendance',['Astra Nova','Monica Bertinelli','Amadeus']),
('Astra Nova','Identité héroïque · Amaelle','Identité héroïque d’Amaelle. Ses interventions et le conflit avec Monica interrogent ce que signifie sauver et jusqu’où va la responsabilité d’une héroïne.',['Astra Nova'],'Descendance',['Amaelle Shirogane','Monica Bertinelli']),
('Elior Vale','Transmission · Combattant','Combattant et figure de transmission. Il participe à l’entraînement d’Amadeus et aux crises qui touchent les êtres conceptuels.',['Elior Vale','Elior'],'Alliés',['Amadeus','Ama Girls']),
('Monica Bertinelli','Adversaire humaine · Spin-off','Voix des victimes oubliées, Monica conteste publiquement Astra Nova et transforme sa douleur en confrontation. Le spin-off suit leur combat, ses conséquences et la possibilité d’une réparation.',['Monica Bertinelli','Monica'],'Humains',['Astra Nova','Andrea Bertinelli']),
('Andrea Bertinelli','Famille · Spin-off','Personnage de la famille Bertinelli, présent dans le parcours de Monica. Les passages du spin-off permettent de suivre précisément leur relation.',['Andrea Bertinelli','Andrea'],'Humains',['Monica Bertinelli']),
('Iver Birkeland','Nouvelle génération','Enfant dont la naissance est racontée dans la fin du tome 9, à Oslo. Une vie humaine qui commence au terme des conflits cosmiques.',['Iver Birkeland','Iver'],'Humains',[]),
]
for row in characters:add('personnages',*row[:4],group=row[4],related=row[5])
for name in ['Amanda','Amandine','Amada','Amalia','Amarilys','Amarisa']:
 add('personnages',name+' Absolute','Double absolu · Doute','Version absolue affrontée pendant l’arc du Doute. La fiche rassemble ses apparitions et le duel avec son pendant Shirogane.',[name+' Absolute','Absolute '+name],group='Absolues',related=[name+' Shirogane','Cael Virelios'])
worlds=[
('Néant','Origine · Mer Blanche','Domaine de Nyxara et espace antérieur aux structures ordinaires. Ses profondeurs et niveaux sont explorés au fil des apprentissages.',['Néant','Mer Blanche'],['Nyxara Abyssgarde','Amavelle Shirogane']),
('Plan de la Conscience','Plan conceptuel','Lieu associé à la Conscience, à la création des entités et à la mise en place des fonctions cosmiques.',['Plan de la Conscience'],['Conscience','Amado Shirogane']),
('Intermonde','Entre les mondes','Espace de passage et de missions où les anomalies et les Rupturus mettent les règles à l’épreuve.',['Intermonde'],['Rupturus','Ama Girls']),
('Zone Rupturus','Contradictions','Espace associé aux contradictions et à leur hiérarchie. Les niveaux des Rupturus y sont décrits et affrontés.',['Zone Rupturus','zone de Rupturus'],['Rupturus','Noxelyra Ordine']),
('Univers du Temps Absolu','Univers temporel','Univers gouverné par Orphéa, avec ses strates, ses responsables temporels et ses menaces sur la continuité.',['Univers du Temps Absolu','UTA'],['Orphéa Aurora','Arion Valerius','Chronophages']),
('Domaine du Nihilisme','Domaine · Nulla','Domaine lié à Nulla Absentia. Les passages sources décrivent sa place après les bouleversements du Doute.',['Domaine du Nihilisme'],['Nulla Absentia','Rebecca Shirogane','Iris Marthory-Vaucluse']),
('Domaine du Doute','Domaine · Cael','Espace du Doute et de ses jugements. Ses transformations accompagnent le dernier grand conflit.',['Domaine du Doute','Tribunal du Doute'],['Cael Virelios','Balance de la Certitude']),
('Désert de l’Idéal','Atelier · Esthétique','Espace d’Iris où les formes et les designs prennent une place matérielle. Le corpus explore également un cimetière de designs rejetés.',['Désert de l’Idéal','Désert de l\'Idéal','Cimetière des Designs Rejetés'],['Iris Marthory-Vaucluse']),
('Terre','Monde humain','Monde des sociétés humaines et des Wardens. Les missions continentales, la vie quotidienne et les conséquences des conflits cosmiques y prennent corps.',['Terre'],['Wardens','Résidence Shirogane']),
('Résidence Shirogane','Japon · Foyer','Foyer de la famille Shirogane. Lieu de repos, de disputes, d’éducation et de vie quotidienne entre les missions.',['Résidence Shirogane','résidence'],['Amado Shirogane','Ama Girls']),
('Point de Convergence','Réseau · Wardens','Lieu de rencontre et de résonance des sept Wardens, servant à coordonner leur protection de la Terre.',['Point de Convergence','Point de Résonance'],['Wardens']),
]
for row in worlds:add('mondes',*row[:4],related=row[4])
for name,col,person in [('Rubis','Vérité','Amanda'),('Doré','Liberté','Amandine'),('Émeraude','Vivant','Amada'),('Saphir','Harmonie','Amalia'),('Argenté','Perfection','Amarilys'),('Améthyste','Logique','Amarisa')]:
 add('mondes','Monde '+name,col+' · Monde des Ama Girls','Monde conceptuel lié à '+person+'. Sa géographie, ses réactions et ses transformations sont racontées dans les chapitres sources.',['Monde '+name,'monde '+name.lower()],related=[person+' Shirogane'])
add('mondes','Monde du Silence','Silence · Amavelle','Monde d’Amavelle, où s’éveille Silentium.',['Monde du Silence'],related=['Amavelle Shirogane','Silentium'])
artifacts=[('Logos','Épée conceptuelle','Épée d’Amado, offerte par la Conscience. Elle tranche ce qui n’a pas de forme et intervient dans le maintien de la cohérence.','Amado Shirogane'),('Ink Genesis','Pinceau · Encre','Artefact créateur de Rebecca, associé aux manifestations de l’encre et à la mise en forme des créations.','Rebecca Shirogane'),('Téganon','Poêle · Sens','Artefact de Noésis, dont la forme quotidienne accompagne une puissance conceptuelle.','Noésis Absoluta'),('Veritas','Lance · Vérité','Arme d’Amanda, forgée dans le monde rubis et employée pour porter la Vérité.','Amanda Shirogane'),('Heliona','Arc solaire · Liberté','Arc et flèches d’Amandine, matérialisés par une lumière solaire.','Amandine Shirogane'),('Lifebloom','Fouet vivant · Nature','Fouet végétal d’Amada, apparu dans son monde vivant.','Amada Shirogane'),('Seijun','Lame · Perfection','Arme d’Amarilys, au cœur de sa pratique de l’épée et de ses duels.','Amarilys Shirogane'),('Logion','Logique','Artefact d’Amarisa, associé à ses raisonnements et aux affrontements de lois.','Amarisa Shirogane'),('Silentium','Marteau · Silence','Marteau d’Amavelle, au manche noir mat et à la tête massive mauve, sans vibration.','Amavelle Shirogane'),('Originis','Hache conceptuelle','Hache de Mirea, qui accompagne ses interventions de Silence.','Mirea Silenshade'),('Fatalis','Pistolets · Ordre','Armes de Vara, employées dans ses opérations de correction.','Vara Ordeline'),('Echron','Râteau cosmique · Rêves','Artefact de Lysenne, utilisé dans ses interventions oniriques.','Lysenne Dreamveil'),('Temporis','Faux · Temps','Arme d’Orphéa, engagée dans les duels entre le Temps et l’Éternité.','Orphéa Aurora'),('Aethernox','Épée du Temps','Épée d’Arion, dont le tranchant corrige ce qu’il touche.','Arion Valerius'),('Aphanéion','Sabre · Temps rejeté','Lame de Chronosia, liée aux réalités et trajectoires qui ont été rejetées.','Chronosia'),('Aethernis','Lance · Éternité','Lance de Kairosia, contenant la mémoire du premier instant immobile de son univers.','Kairosia Aethern'),('Aporia','Épée · Doute','Épée de Cael, employée notamment pour ouvrir la fissure d’où naît Nyra.','Cael Virelios'),('Balance de la Certitude','Instrument · Doute','Instrument du jugement de Cael. Ses apparitions montrent comment il évalue les certitudes et les existences.','Cael Virelios'),('Éon','Épée · Béhémoth','Épée de Béhémoth, détruite à la fin de l’affrontement avec les sept Wardens.','Béhémoth')]
for name,sub,summ,person in artifacts:add('artefacts',name,sub,summ,related=[person])
concepts=[('Conscience','Origine','Présence créatrice à l’origine d’Amado et des structures conceptuelles.'),('Raison','Loi · Amado','Principe de cohérence et d’arbitrage incarné par Amado.'),('Sens','Loi · Noésis','Principe qui donne une direction et une signification à l’existence.'),('Doute','Loi · Cael','Remise en question devenue une force capable de juger les certitudes de l’univers.'),('Nihilisme','Concept · Nulla','Opposition au sens et interrogation sur la valeur de l’existence.'),('Esthétique','Concept · Iris','Travail de la forme, des lignes et de la beauté des existences.'),('Résonance','Coopération','Interaction de forces ou d’émotions permettant des réponses communes.'),('Silence','Concept','Concept incarné et pratiqué de différentes manières par Mirea et Amavelle.'),('Ordre','Concept','Principe structurant lié à Vara et aux opérations de correction.'),('Rêves','Concept','Espace de repos mental et d’équilibrage lié à Lysenne.'),('Qi','Énergie · Asie','Flux énergétiques que Lian Yue stabilise et que Jīn-Luàn attaque.'),('Immortalité','Règle · Vulnérabilité','Le récit distingue l’immortalité de l’invincibilité, notamment dans l’expérience humaine d’Amaelle.'),('Double Ancrage','Méthode','Méthode nommée dans les entraînements et les situations de combat. Ses applications sont réunies ici.'),('Suspension Blanche','Technique · Séraphyne','Technique employée par Séraphyne lors du combat final des Wardens contre Béhémoth.'),('Hydro-mimétisme','Pouvoir · Avelyn','Faculté d’absorption, d’imitation et d’adaptation associée à la Warden de l’Océanie.')]
for row in concepts:add('concepts',*row)
groups=[('Ama Girls','Sept sœurs','Ensemble des sœurs conceptuelles : Amanda, Amandine, Amada, Amalia, Amarilys, Amarisa et Amavelle.'),('Wardens','Sept gardiennes de la Terre','Gardiennes continentales liées aux flux humains et aux équilibres de la Terre.'),('Servantes conceptuelles','Silence · Ordre · Rêves','Mirea, Vara et Lysenne accompagnent l’éducation et la progression des Ama Girls.'),('Chronophages','Menaces temporelles','Menaces affrontées dans l’Univers du Temps Absolu, notamment pendant les opérations de restauration.'),('Rupturus','Contradictions incarnées','Existences issues de contradictions, avec des niveaux et des formes que le récit distingue progressivement.'),('Cavaliers','Famine · Oppression · Eros','Les trois figures Limos, Kratos et Eros interviennent dans l’attaque de la Terre pendant le conflit du Doute.'),('Fléaux','Menaces terrestres','Manifestations affrontées sur Terre pendant les voyages et les missions des Wardens.'),('Barbatos','Menace · Néant','Adversaire de Nyxara au cours de l’exploration des profondeurs.'),('Cénotaphe','Existence · Rupturus','Existence rencontrée dans le parcours lié aux contradictions et aux domaines.'),('Chrona Residua','Menace temporelle','Adversaire d’Arion Valerius dans le tome 5.'),('Egregor Nullstahl','Fléau · Europe','Adversaire d’Anastasia au cours des missions européennes.'),('Huracàn Obscura','Fléau · Amérique du Sud','Adversaire de Lysandra Monteiro dans le tome 1.'),('Mikagura','Duel des lois','Adversaire rencontré dans les confrontations des premières Ama Girls.'),('Rift-Kraken','Fléau océanique','Menace affrontée dans les épisodes de la fin du tome 2 et du début du tome 3.')]
for row in groups:add('factions',*row)
# Arcs are editorial reading routes, never claimed to be official titles or canonical boundaries.
arcspec=[
('Genèse et premiers mondes',1,0,1,85,'Naissance d’Amado, des Ama Girls et des Servantes ; création des mondes, premières résonances et confrontation aux anomalies.'),
('Voyages terrestres et Wardens',1,86,3,316,'Missions continentales, rencontres avec les sept Wardens et découverte des sociétés humaines.'),
('Apprentissages et contradictions',3,317,3,436,'Nouveaux apprentissages, hiérarchie des Rupturus, domaines stabilisés et interrogation de la cohérence.'),
('Temps, Nihilisme et restauration',4,437,4,608,'Crise temporelle, affrontement de Noésis et Nulla, responsabilités dans l’Univers du Temps Absolu et apparition de Chronosia.'),
('Duels et continuité',5,609,5,739,'Confrontations entre fonctions, héritages et interventions sur la continuité temporelle.'),
('Profondeurs du Néant',6,740,6,802,'Exploration des niveaux du Néant, nature de Nyxara et affrontement avec Barbatos.'),
('Béhémoth et les sept Wardens',6,803,6,859,'Crise planétaire, combats des lieutenants et convergence finale des Wardens contre Béhémoth.'),
('Héritage et vie humaine',6,860,7,939,'Éducation, vulnérabilité, descendance et émergence d’Astra Nova dans la vie humaine.'),
('Conflit de l’Éternité',7,940,7,983,'Orphéa face à Kairosia ; affrontements des fonctions temporelles avec leurs contrepoints.'),
('Transmission et départs',7,984,7,1043.5,'Parcours humains, apprentissages et retour au flux avant la naissance du Doute.'),
('Arc du Doute',8,1044,9,1175,'Genèse de Cael, Instabilité de Nyra, Cavaliers, doubles absolus et affrontement final avec Amadeus.'),
]
for i,(name,ta,ca,tb,cb,summary) in enumerate(arcspec):
 chosen=[]
 for c in cs:
  if ta<=c['tome']<=tb:
   m=re.search(r'(?i)chapi(?:tre|re)\s+(?:bonus\s+)?(\d+(?:\.\d+)?)',c['title']);num=float(m[1]) if m else None
   if num is not None and (c['tome']>ta or num>=ca) and (c['tome']<tb or num<=cb):chosen.append(c)
 if chosen:entries.append({'id':f'arc-{i+1}','category':'arcs','name':name,'subtitle':f'Tome {ta}'+(f'–{tb}' if tb!=ta else '')+' · Parcours de lecture','summary':summary,'aliases':[name],'group':'Série principale','related':[],'sources':[{'chapter':c['id'],'tome':c['tome'],'page':c['start'],'quote':c['title']} for c in chosen[:3]],'chapters':[c['id'] for c in chosen],'occurrences':len(chosen),'first':chosen[0]['id'],'tomes':sorted(set(c['tome'] for c in chosen)),'editorial':True})
for part,name,summary in [(1,'Premiers règnes de l’Éternité','Le règne de Kairosia et ses relations avec les forces primordiales.'),(2,'Astra Nova et Monica Bertinelli','Responsabilité héroïque, victimes oubliées, procès public et confrontation au parc Solaris.'),(3,'Iris et les formes humaines','L’Esthétique face aux corps imparfaits, aux rencontres et à la vie humaine.')]:
 chosen=[c for c in cs if c['tome']==10 and c['part']==part]
 entries.append({'id':f'spin-off-{part}','category':'arcs','name':name,'subtitle':'Tome 10 · Spin-off','summary':summary,'group':'Spin-off','aliases':[name],'related':[],'sources':[{'chapter':c['id'],'tome':10,'page':c['start'],'quote':c['title']} for c in chosen[:3]],'chapters':[c['id'] for c in chosen],'first':chosen[0]['id'],'tomes':[10],'editorial':True})
# Combat dossiers anchored to explicit chapter titles, with the full chapter available.
for c in cs:
 if re.search(r'\bvs\b|\bcontre\b',c['title'],re.I):
  title=re.sub(r'(?i)^chapitre\s+(?:bonus\s*)?(?:\d+(?:\.\d+)?\s*(?:bonus)?\s*)?[:—–-]\s*','',c['title']).strip()
  entries.append({'id':'combat-'+c['id'],'category':'combats','name':title,'subtitle':f'Tome {c["tome"]} · p. {c["start"]}–{c["end"]}','summary':'Affrontement documenté dans « '+c['title']+' ». Retrouvez le contexte, les actions et les conséquences dans le passage intégral.','aliases':[title],'group':'Duels','related':[],'sources':[{'chapter':c['id'],'tome':c['tome'],'page':c['start'],'quote':c['pages'][0]['text'][:650]}],'chapters':[c['id']],'first':c['id'],'tomes':[c['tome']]})
# Documented conclusions, without speculative power rankings.
conclusions={'t7-c44':('Le premier échange s’achève à puissance égale au chapitre 946. La prise du trône et la suite du conflit sont racontées dans les chapitres suivants.','t7-c46'),'t7-c65':('Victoire de Chroniel : le Paradoxe est vaincu au chapitre 967.','t7-c67'),'t9-c34':('Victoire d’Amarisa Shirogane sur Amarisa Absolute au chapitre 1152.','t9-c36'),'t6-c109':('Victoire des sept Wardens. Béhémoth est réduite à zéro au chapitre 854.','t6-c115'),'t9-c43':('Cael est vaincu au chapitre 1167 ; les Absolues sont vaincues et Noésis revient.','t9-c52'),'t10-c19':('Victoire d’Astra Nova. Elle neutralise Monica par un coup maîtrisé et la rattrape avant sa chute.','t10-c19'),'t9-c5':('Victoire de Noxelyra et Nulla : l’incarnation de Nyra est détruite au chapitre 1127 ; le concept d’Instabilité redevient abstrait.','t9-c10'),'t9-c6':('Victoire de Noxelyra et Nulla : l’incarnation de Nyra est détruite au chapitre 1127 ; le concept d’Instabilité redevient abstrait.','t9-c10')}
for e in entries:
 if e['category']=='combats' and e['first'] in conclusions:
  txt,cid=conclusions[e['first']];e['outcome']=txt;c=next(c for c in cs if c['id']==cid);e['chapters']=list(dict.fromkeys(e['chapters']+[cid]));e['sources'].append({'chapter':cid,'tome':c['tome'],'page':c['start'],'quote':c['title']})
# Source-backed identity and power passages, kept as excerpts rather than speculative statistics.
facetspec=[('Apparence',r'cheveux|yeux|lunettes|kimono|armure|robe|costume|tenue'),('Pouvoirs et méthodes',r'pouvoir|capable|technique|incarn|arme|essence|ancrage'),('Évolution et conséquences',r'hérit|transform|absor|naissance|scell|défaite|vaincu|mort|création')]
for e in entries:
 if e['category']!='personnages':continue
 patterns=[re.compile(r'(?<!\w)'+r'\s+'.join(re.escape(w) for w in norm(a).split())+r'(?!\w)') for a in e['aliases']]
 facets=[]
 for label,terms in facetspec:
  choices=[];seen=set()
  for c in cs:
   if c['id'] not in e['chapters']:continue
   for p in c['pages']:
    text=p['text'];nt=norm(text); namehits=[m for pat in patterns for m in pat.finditer(nt)]
    for m in namehits:
     a=max(0,m.start()-100);b=min(len(text),m.end()+500);window=text[a:b]
     if re.search(terms,window,re.I) and (c['id'] not in seen):
      choices.append({'chapter':c['id'],'tome':c['tome'],'page':p['page'],'quote':window.strip()});seen.add(c['id']);break
  if choices:facets.append({'name':label,'sources':choices[:2]+(choices[-1:] if len(choices)>2 else [])})
 e['facets']=facets
# Link references to actual dossier IDs.
lookup={e['name']:e['id'] for e in entries}
for e in entries:e['links']=[{'name':n,'id':lookup[n]} for n in e.get('related',[]) if n in lookup]
metadata={'entries':entries,'stats':{'tomes':10,'pages':8791,'chapters':len(cs),'dossiers':len(entries)},'note':'Synthèses tirées des dix PDF fournis. Les arcs sont des regroupements éditoriaux de lecture ; les noms de chapitres et les références de pages reproduisent les sources. Les variations de noms sont conservées dans les alias.'}
(ROOT/'dist/data/wiki.js').write_text('window.SH_WIKI='+json.dumps(metadata,ensure_ascii=False,separators=(',',':'))+';')
print(collections.Counter(e['category'] for e in entries),len(entries))
