const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright' : 'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:393,height:851},deviceScaleFactor:1});
 const page=await context.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.resolve(__dirname,'../app/src/main/assets/index.html'));
 assert.equal(await page.locator('.idea').count(),30);
 await page.screenshot({path:'/tmp/etincelle-home.png',fullPage:false});
 await page.locator('[data-cat="tech"]').click();assert.equal(await page.locator('.idea').count(),5);
 await page.locator('#search').fill('réseau');assert.equal(await page.locator('.idea').count(),2);
 await page.locator('#search').fill('zzzzzzzz');assert.equal(await page.locator('.idea').count(),0);
 await page.locator('#search').fill('');
 await page.locator('[data-open="repair"]').click();
 await page.locator('#notes').fill('Mon prototype <script>alert(1)</script> & mes notes');
 await page.locator('#detail [data-save="repair"]').click();
 await page.locator('#close').click();
 await page.reload();
 await page.locator('[data-tab="saved"]').click();assert.equal(await page.locator('.idea').count(),1);
 await page.locator('[data-open="repair"]').click();assert.equal(await page.locator('#notes').inputValue(),'Mon prototype <script>alert(1)</script> & mes notes');
 await page.locator('#close').click();
 await page.locator('[data-tab="studio"]').click();
 await page.locator('#domain').selectOption('tech');await page.locator('#level').selectOption('Facile');await page.locator('#angle').selectOption('privacy');
 await page.locator('#studioForm button').click();
 assert.equal(await page.locator('#studioResult .idea').count(),1);
 const first=await page.locator('#studioResult h3').textContent();assert(first.endsWith(' Privé'));
 await page.locator('#studioForm button').click();assert.notEqual(await page.locator('#studioResult h3').textContent(),first);
 await page.locator('#studioResult .bookmark').click();
 await page.locator('#studioResult .open').click();assert((await page.locator('#detailBody').innerText()).includes('Confidentialité'));
 await page.screenshot({path:'/tmp/etincelle-detail.png'});
 assert.equal(await page.evaluate(()=>window.handleBack()),true);
 await page.locator('#domain').selectOption('daily');await page.locator('#level').selectOption('Avancé');await page.locator('#studioForm button').click();
 assert.equal(await page.locator('#studioResult .idea').count(),0);assert((await page.locator('#studioResult').innerText()).includes('Pas de concept'));
 await page.locator('[data-tab="saved"]').click();assert.equal(await page.locator('.idea').count(),2);
 await page.reload();await page.locator('[data-tab="saved"]').click();assert.equal(await page.locator('.idea').count(),2);
 await page.locator('.bookmark').first().click();assert.equal(await page.locator('.idea').count(),1);
 await page.setViewportSize({width:320,height:650});await page.locator('[data-tab="discover"]').click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.setViewportSize({width:1000,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 const {IDEAS,ANGLES}=require('../app/src/main/assets/ideas.js');
 assert.equal(new Set(IDEAS.map(x=>x.id)).size,30);assert.equal(IDEAS.length*Object.keys(ANGLES).length,150);
 for(const x of IDEAS){assert.equal(x.features.length,3);for(const k of ['name','pitch','problem','audience','money','validation','tech'])assert(x[k]?.length>5)}
 console.log('PASS: 30 concepts, 150 combinaisons, filtres, recherche, fiches, favoris, notes persistantes, sécurité texte, studio, états vides, retour, responsive, aucune erreur JavaScript.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
